-- ============================================================================
-- SEED: 93 Controles ISO 27001:2022 Anexo A
-- ============================================================================

-- DOMINIO 5: CONTROLES ORGANIZACIONALES (37 controles)
INSERT INTO `controles` (`dominio_id`, `codigo`, `nombre`, `descripcion`, `objetivo`) VALUES
(1, '5.1', 'Políticas de seguridad de la información', 'Establecer políticas de seguridad de la información aprobadas por la dirección', 'Proporcionar dirección y apoyo de la gestión para la seguridad de la información'),
(1, '5.2', 'Roles y responsabilidades de seguridad de la información', 'Definir y asignar roles y responsabilidades de seguridad', 'Establecer rendición de cuentas clara'),
(1, '5.3', 'Segregación de funciones', 'Separar funciones incompatibles', 'Reducir oportunidades de modificación no autorizada'),
(1, '5.4', 'Responsabilidades de la dirección', 'Asegurar apoyo y compromiso de la dirección', 'Garantizar recursos adecuados'),
(1, '5.5', 'Contacto con autoridades', 'Mantener contactos apropiados con autoridades', 'Facilitar cumplimiento legal'),
(1, '5.6', 'Contacto con grupos de interés especial', 'Mantener contactos con grupos especializados', 'Mantenerse actualizado en amenazas'),
(1, '5.7', 'Inteligencia de amenazas', 'Recopilar y analizar información sobre amenazas', 'Identificar amenazas relevantes'),
(1, '5.8', 'Seguridad de la información en la gestión de proyectos', 'Integrar seguridad en gestión de proyectos', 'Proteger proyectos desde el inicio'),
(1, '5.9', 'Inventario de información y otros activos asociados', 'Identificar activos de información', 'Gestionar y proteger activos apropiadamente'),
(1, '5.10', 'Uso aceptable de la información y otros activos asociados', 'Definir reglas de uso aceptable', 'Prevenir uso indebido'),
(1, '5.11', 'Devolución de activos', 'Procedimientos de devolución de activos al terminar empleo', 'Proteger activos al final de relación laboral'),
(1, '5.12', 'Clasificación de la información', 'Clasificar información según importancia', 'Garantizar nivel de protección apropiado'),
(1, '5.13', 'Etiquetado de la información', 'Etiquetar información según clasificación', 'Indicar nivel de protección requerido'),
(1, '5.14', 'Transferencia de información', 'Reglas para transferencia de información', 'Proteger información en tránsito'),
(1, '5.15', 'Control de acceso', 'Reglas de control de acceso', 'Limitar acceso a información autorizada'),
(1, '5.16', 'Gestión de identidad', 'Gestionar identidades de usuarios', 'Identificar usuarios únicamente'),
(1, '5.17', 'Información de autenticación', 'Gestionar información de autenticación', 'Proteger credenciales'),
(1, '5.18', 'Derechos de acceso', 'Provisión y gestión de derechos de acceso', 'Asegurar acceso apropiado'),
(1, '5.19', 'Seguridad de la información en las relaciones con proveedores', 'Gestionar seguridad con proveedores', 'Mantener nivel de seguridad con terceros'),
(1, '5.20', 'Abordar la seguridad de la información en los acuerdos con proveedores', 'Incluir requisitos de seguridad en contratos', 'Formalizar obligaciones de seguridad'),
(1, '5.21', 'Gestión de la seguridad de la información en la cadena de suministro de TIC', 'Gestionar riesgos en cadena de suministro', 'Asegurar proveedores de TIC'),
(1, '5.22', 'Monitoreo, revisión y gestión de cambios de servicios de proveedores', 'Monitorear servicios de proveedores', 'Mantener nivel acordado de seguridad'),
(1, '5.23', 'Seguridad de la información para el uso de servicios en la nube', 'Gestionar seguridad en servicios cloud', 'Proteger información en la nube'),
(1, '5.24', 'Planificación y preparación de la gestión de incidentes de seguridad de la información', 'Planificar respuesta a incidentes', 'Responder efectivamente a incidentes'),
(1, '5.25', 'Evaluación y decisión sobre eventos de seguridad de la información', 'Evaluar eventos de seguridad', 'Clasificar incidentes correctamente'),
(1, '5.26', 'Respuesta a incidentes de seguridad de la información', 'Responder a incidentes confirmados', 'Minimizar impacto'),
(1, '5.27', 'Aprender de los incidentes de seguridad de la información', 'Analizar lecciones aprendidas', 'Prevenir recurrencia'),
(1, '5.28', 'Recopilación de evidencia', 'Recopilar evidencia forense', 'Preservar evidencia legal'),
(1, '5.29', 'Seguridad de la información durante la interrupción', 'Mantener seguridad durante interrupciones', 'Asegurar continuidad de seguridad'),
(1, '5.30', 'Preparación de las TIC para la continuidad del negocio', 'Preparar TIC para continuidad', 'Garantizar disponibilidad de TIC'),
(1, '5.31', 'Requisitos legales, estatutarios, reglamentarios y contractuales', 'Identificar requisitos legales aplicables', 'Asegurar cumplimiento legal'),
(1, '5.32', 'Derechos de propiedad intelectual', 'Proteger propiedad intelectual', 'Cumplir requisitos de PI'),
(1, '5.33', 'Protección de registros', 'Proteger registros importantes', 'Preservar evidencia y registros'),
(1, '5.34', 'Privacidad y protección de información personal identificable', 'Proteger información personal', 'Cumplir requisitos de privacidad'),
(1, '5.35', 'Revisión independiente de la seguridad de la información', 'Realizar revisiones independientes', 'Verificar efectividad de controles'),
(1, '5.36', 'Cumplimiento de políticas, reglas y normas de seguridad de la información', 'Asegurar cumplimiento de políticas', 'Verificar adherencia a requisitos'),
(1, '5.37', 'Procedimientos operativos documentados', 'Documentar procedimientos operativos', 'Garantizar operación correcta'),

-- DOMINIO 6: CONTROLES DE PERSONAS (8 controles)
(2, '6.1', 'Selección', 'Verificación de antecedentes en contratación', 'Reducir riesgos de personal'),
(2, '6.2', 'Términos y condiciones de empleo', 'Definir responsabilidades de seguridad en contratos', 'Formalizar obligaciones de empleados'),
(2, '6.3', 'Concienciación, educación y capacitación en seguridad de la información', 'Capacitar personal en seguridad', 'Desarrollar competencias de seguridad'),
(2, '6.4', 'Proceso disciplinario', 'Proceso disciplinario formal', 'Abordar violaciones de seguridad'),
(2, '6.5', 'Responsabilidades después de la terminación o cambio de empleo', 'Gestionar responsabilidades al terminar empleo', 'Proteger intereses organizacionales'),
(2, '6.6', 'Acuerdos de confidencialidad o no divulgación', 'Acuerdos de confidencialidad con personal', 'Proteger información confidencial'),
(2, '6.7', 'Trabajo remoto', 'Seguridad para trabajo remoto', 'Proteger información fuera de instalaciones'),
(2, '6.8', 'Reporte de eventos de seguridad de la información', 'Canales para reportar eventos', 'Detectar incidentes tempranamente'),

-- DOMINIO 7: CONTROLES FÍSICOS (14 controles)
(3, '7.1', 'Perímetros de seguridad física', 'Definir perímetros de seguridad', 'Prevenir acceso físico no autorizado'),
(3, '7.2', 'Entrada física', 'Controlar entrada a áreas seguras', 'Restringir acceso físico'),
(3, '7.3', 'Seguridad de oficinas, recintos e instalaciones', 'Diseñar seguridad física de instalaciones', 'Proteger instalaciones y activos'),
(3, '7.4', 'Monitoreo de seguridad física', 'Monitorear instalaciones continuamente', 'Detectar acceso no autorizado'),
(3, '7.5', 'Protección contra amenazas físicas y ambientales', 'Proteger contra desastres naturales', 'Prevenir daño físico'),
(3, '7.6', 'Trabajo en áreas seguras', 'Reglas para trabajar en áreas seguras', 'Proteger áreas sensibles'),
(3, '7.7', 'Escritorio limpio y pantalla limpia', 'Política de escritorio y pantalla limpios', 'Reducir riesgo de acceso no autorizado'),
(3, '7.8', 'Ubicación y protección de equipos', 'Ubicar equipos apropiadamente', 'Reducir riesgos ambientales'),
(3, '7.9', 'Seguridad de los activos fuera de las instalaciones', 'Proteger activos fuera de instalaciones', 'Mantener seguridad fuera del sitio'),
(3, '7.10', 'Medios de almacenamiento', 'Gestionar medios de almacenamiento', 'Prevenir divulgación no autorizada'),
(3, '7.11', 'Servicios de soporte', 'Asegurar servicios de soporte', 'Mantener disponibilidad de servicios'),
(3, '7.12', 'Seguridad del cableado', 'Proteger cables de datos y energía', 'Prevenir interceptación'),
(3, '7.13', 'Mantenimiento de equipos', 'Mantener equipos correctamente', 'Garantizar disponibilidad continua'),
(3, '7.14', 'Eliminación o reutilización segura de equipos', 'Borrado seguro de equipos', 'Prevenir fuga de información'),

-- DOMINIO 8: CONTROLES TECNOLÓGICOS (34 controles)
(4, '8.1', 'Dispositivos de punto final de usuario', 'Proteger dispositivos de usuarios', 'Asegurar puntos finales'),
(4, '8.2', 'Derechos de acceso privilegiado', 'Gestionar accesos privilegiados', 'Controlar accesos administrativos'),
(4, '8.3', 'Restricción de acceso a la información', 'Restringir acceso según política', 'Aplicar principio de menor privilegio'),
(4, '8.4', 'Acceso al código fuente', 'Controlar acceso a código fuente', 'Proteger propiedad intelectual'),
(4, '8.5', 'Autenticación segura', 'Implementar autenticación fuerte', 'Verificar identidad de usuarios'),
(4, '8.6', 'Gestión de capacidad', 'Monitorear y gestionar capacidad', 'Asegurar rendimiento adecuado'),
(4, '8.7', 'Protección contra malware', 'Detectar y prevenir malware', 'Proteger contra código malicioso'),
(4, '8.8', 'Gestión de vulnerabilidades técnicas', 'Identificar y remediar vulnerabilidades', 'Reducir superficie de ataque'),
(4, '8.9', 'Gestión de configuración', 'Gestionar configuraciones de seguridad', 'Mantener configuraciones seguras'),
(4, '8.10', 'Eliminación de información', 'Eliminar información apropiadamente', 'Prevenir recuperación no autorizada'),
(4, '8.11', 'Enmascaramiento de datos', 'Enmascarar datos sensibles', 'Proteger datos en ambientes no productivos'),
(4, '8.12', 'Prevención de fuga de datos', 'Prevenir exfiltración de datos', 'Detectar y bloquear fugas'),
(4, '8.13', 'Respaldo de información', 'Respaldar información regularmente', 'Asegurar recuperación de datos'),
(4, '8.14', 'Redundancia de instalaciones de procesamiento de información', 'Implementar redundancia', 'Garantizar disponibilidad continua'),
(4, '8.15', 'Registro', 'Registrar eventos relevantes', 'Mantener evidencia de actividades'),
(4, '8.16', 'Actividades de monitoreo', 'Monitorear sistemas continuamente', 'Detectar actividades anómalas'),
(4, '8.17', 'Sincronización de reloj', 'Sincronizar relojes de sistemas', 'Garantizar correlación de eventos'),
(4, '8.18', 'Uso de programas de utilidad privilegiados', 'Controlar uso de utilidades privilegiadas', 'Prevenir uso indebido'),
(4, '8.19', 'Instalación de software en sistemas operativos', 'Controlar instalación de software', 'Prevenir software no autorizado'),
(4, '8.20', 'Seguridad de redes', 'Proteger redes de datos', 'Asegurar comunicaciones'),
(4, '8.21', 'Seguridad de servicios de red', 'Asegurar servicios de red', 'Proteger servicios críticos'),
(4, '8.22', 'Segregación de redes', 'Segregar redes lógicamente', 'Aislar sistemas críticos'),
(4, '8.23', 'Filtrado web', 'Filtrar acceso web', 'Prevenir acceso a sitios maliciosos'),
(4, '8.24', 'Uso de criptografía', 'Implementar criptografía apropiada', 'Proteger confidencialidad e integridad'),
(4, '8.25', 'Ciclo de vida de desarrollo seguro', 'Integrar seguridad en desarrollo', 'Desarrollar software seguro'),
(4, '8.26', 'Requisitos de seguridad de aplicaciones', 'Definir requisitos de seguridad', 'Construir aplicaciones seguras'),
(4, '8.27', 'Arquitectura de sistemas seguros y principios de ingeniería', 'Diseñar arquitecturas seguras', 'Integrar seguridad en diseño'),
(4, '8.28', 'Codificación segura', 'Aplicar prácticas de codificación segura', 'Prevenir vulnerabilidades'),
(4, '8.29', 'Pruebas de seguridad en desarrollo y aceptación', 'Probar seguridad en SDLC', 'Identificar vulnerabilidades temprano'),
(4, '8.30', 'Desarrollo externalizado', 'Gestionar desarrollo externalizado', 'Asegurar código de terceros'),
(4, '8.31', 'Separación de ambientes de desarrollo, prueba y producción', 'Segregar ambientes', 'Prevenir cambios no autorizados'),
(4, '8.32', 'Gestión de cambios', 'Gestionar cambios formalmente', 'Controlar modificaciones'),
(4, '8.33', 'Información de prueba', 'Proteger datos de prueba', 'Prevenir exposición de datos reales'),
(4, '8.34', 'Protección de sistemas de información durante pruebas de auditoría', 'Proteger sistemas durante auditorías', 'Prevenir impacto operacional');
